/*
 * Copyright (C) 2017-2017 DataStax Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datastax.oss.driver.api.core.metadata.schema;

import com.datastax.oss.driver.api.core.CqlIdentifier;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/** A table or materialized view in the schema metadata. */
public interface RelationMetadata extends Describable {

  KeyspaceMetadata getKeyspace();

  CqlIdentifier getName();

  /** The unique id generated by the server for this element. */
  UUID getId();

  List<ColumnMetadata> getPartitionKey();

  Map<ColumnMetadata, ClusteringOrder> getClusteringColumns();

  Map<CqlIdentifier, ColumnMetadata> getColumns();

  TableOptionsMetadata getOptions();
}
